# antiscraper docker compose configuration.
services:
  # incoming connections will be routed through anubis
  anubis:
    image: ghcr.io/techarohq/anubis:latest
    environment:
      # Port for incoming traffic
      BIND: ":8080"
      DIFFICULTY: "1"
      METRICS_BIND: ":9090"
      SERVE_ROBOTS_TXT: "false" # we'll use nginx + iocaine for that
      # Target for accepted connections
      TARGET: "http://proxy:8081"
      POLICY_FNAME: "/tmp/botPolicy.json"
    volumes:
      - "./anubis/botPolicy.json:/tmp/botPolicy.json:ro"
    restart: unless-stopped

  # once they succeed, they will go to caddy for further routing
  proxy:
    image: openresty/openresty
    volumes:
      - "./openresty/nginx.conf.d:/etc/nginx/conf.d"
      - "./openresty/bg_conf:/etc/nginx/bg_conf"
      - "./openresty/lua:/etc/nginx/lua"
    # THIS IS THE ONLY PORT THAT SHOULD BE PUBLICLY EXPOSED
    ports:
      - "${MAIN_PORT:-9999}:80"
    environment:
      TARGET_ENDPOINT: "${TARGET_ENDPOINT:-http://example:80}"
      IOCAINE_ENDPOINT: "http://iocaine:42069"
      ANUBIS_ENDPOINT: "http://anubis:8080"
    restart: unless-stopped
    depends_on:
      - iocaine
      - anubis

  # caddy will route bad requests to iocaine
  iocaine:
    image: git.madhouse-project.org/iocaine/iocaine:2.5.0
    restart: unless-stopped
    volumes:
      - "./iocaine/corpus:/etc/iocaine/corpus"
      - "./iocaine/config.toml:/etc/iocaine/config.toml:ro"
    command: "--config-file /etc/iocaine/config.toml"

#   # Prometheus will collect metrics from all of the other services...
#   prometheus:
#     image: prom/prometheus
#     # you should make sure port 9090 is only accessible from trusted sources
#     # this configuration makes it only available to localhost
#     ports:
#       - "${METRICS_PORT:-9090}:9090"
#     # make metrics data persistent
#     volumes:
#       - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
# #      - "prometheus_data:/data"
#     command:
#       - "--config.file=/etc/prometheus/prometheus.yml"
# #      - "--storage.tsdb.path=/data"
#       - '--web.console.libraries=/usr/share/prometheus/console_libraries'
#       - '--web.console.templates=/usr/share/prometheus/consoles'
#     depends_on:
#       - anubis
#       - iocaine

  # ...and Grafana will provide a nice dashboard
  # grafana:
  #   image: grafana
  #   depends_on:
  #     - prometheus

  # a simple example service that we want to protect
  example:
    image: httpd:2.4
    volumes:
      - "./example/:/usr/local/apache2/htdocs/"
    depends_on:
      - proxy

volumes:
  prometheus_data: