# antiscraper docker compose configuration.
services:
  # incoming connections will be routed through anubis
  anubis:
    image: ghcr.io/techarohq/anubis:latest
    environment:
      # Port for incoming traffic
      BIND: ":8080"
      DIFFICULTY: "1"
      METRICS_BIND: ":9090"
      SERVE_ROBOTS_TXT: "false" # we'll use nginx + iocaine for that
      # Target for accepted connections
      TARGET: "http://proxy:8081"
      POLICY_FNAME: "/data/cfg/botPolicy.json"
    volumes:
      - "./anubis/botPolicy.json:/data/cfg/botPolicy.json:ro"
    restart: unless-stopped
  # once they succeed, they will go to caddy for further routing
  proxy:
    image: caddy
    volumes:
      - "./caddy:/etc/caddy"
    # THIS IS THE ONLY PORT THAT SHOULD BE PUBLICLY EXPOSED
    ports:
      - $MAIN_PORT:8080
    restart: unless-stopped
  # caddy will route bad requests to iocaine
  iocaine:
    image: git.madhouse-project.org/iocaine/iocaine:latest
    restart: unless-stopped
    volumes:
      - "./iocaine/data:/data"
      - "./iocaine/config.toml:/etc/iocaine/config.toml:ro"
    command: "--config-file /etc/iocaine/config.toml"
  # Prometheus will collect metrics from all of the other services.
  metrics:
    image: prom/prometheus
    # you should make sure port 9090 is only accessible from trusted sources
    # this configuration makes it only available to localhost
    ports:
      - 9090:9090
    # make metrics data persistent
    volumes:
      - "./metrics/prometheus.yml:/etc/prometheus/prometheus.yml"
#      - "./metrics/data:/data"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
#      - "--storage.tsdb.path=/data"
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
  # a simple example service that we want to protect
  example:
    image: httpd:2.4
    volumes:
      - "./example/:/usr/local/apache2/htdocs/"