# This is the config file for Bene Gesserit. This is the single source of truth 
# for all configuration parameters, and should be the only place that you make
# configuration changes for the application. The generator script will handle
# creating other configuration files based on this one.

# Enables extra debugging headers if set to true. Disable this in a production
# instance.
debug = true

# This target is the inevitable endpoint that your application will reach.
target = "http://example:80"
# This variable specifies the configuration of your environment. It can either
# be a string (which maps to a pre-configured environment), or a table
# containing all the required values. The environment specifies where files are
# placed, 
environment = "compose"

# This section configures "honeypot" endpoints; Any endpoints that match these
# patterns will automatically be passed into the labyrinth.
[honeypot]
# A set of regex patterns to match.
endpoints = [
    "^/sicily",
    "^/asia"
]
# If set to true, a robots.txt will be generated using the honeypot endpoints.
# This will override your application's default robots.txt.
override_robots = true

# These are examples of the configurable ratelimiting rules.
[[ratelimit.rules]]
rule = "any"
amount = 30
seconds = 5
exclude = [
    "*.js",
    "*.mjs",
    "*.css"
]

[[ratelimit.rules]]
rule = "unique"
total = 15
unique = 5
seconds = 5
exclude = [
    "*.js",
    "*.mjs",
    "*.css"
]

# Configuration parameters for the labyrinth, an endless tree of Markov chain
# generated nonsense. These configurations are used for Iocaine.
[labyrinth]
# After n amount of violations, clients will be permanently sent into the
# labyrinth on all future requests (even to legitimate endpoints). A "client" is
# determined by the cookie set by Anubis on their initial connection. Setting
# this to 0 disables this functionality, and clients will not be permanently
# sent into the labyrinth (just when they trigger violations).
banish_threshold = 3
# The file(s) used to train the Markov chain generator. These should be long
# text files that contain a lot of words. You can select files on your computer
# or arbitrary URLs, or use one of the pre-configured text file services (such
# as Project Gutenberg).
# This example uses the entire works of H. P. Lovecraft, in order to subject
# scrapers to machine-made horrors beyond their comprehension.
# TODO: implement profanity/slur filter
corpus = [
    { gutenberg = 50133 },
    { gutenberg = 31469 },
    { gutenberg = 30637 },
    { gutenberg = 68283 },
    { gutenberg = 70652 },
    { gutenberg = 73181 },
    { gutenberg = 68236 },
    { gutenberg = 73547 },
    { gutenberg = 76113 },
    { gutenberg = 68553 },
    { gutenberg = 71167 },
    { gutenberg = 72966 },
    { gutenberg = 73233 },
    { gutenberg = 70486 },
    { gutenberg = 73230 },
    { gutenberg = 73177 },
    { gutenberg = 70899 },
    { gutenberg = 70912 },
    { gutenberg = 68547 },
    { gutenberg = 73243 },
    { gutenberg = 70478 },
    { gutenberg = 73182 }
]
# A word list URL. This should be a file containing a list of words, separated
# by newlines. These will be used for generating URL paths to link to.
words.url = "https://raw.githubusercontent.com/dwyl/english-words/refs/heads/master/words_alpha.txt"

# Configuration for Prometheus metrics.
[metrics]
enabled = true
