server {
    listen       80;
    server_name  localhost;
    resolver 127.0.0.11 valid=30s;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    location / {
        proxy_pass http://anubis:8080;
        proxy_intercept_errors on;
        error_page 421 @ioc;
    }

    location @ioc {
        proxy_pass http://iocaine:42069;
    }
}

server {
    listen 8081;
    server_name localhost;
    resolver 127.0.0.11 valid=30s;

    location / {
        set $upstream_target http://example:80;

        rewrite_by_lua_block {
            local file_path = "/etc/nginx/bg_conf/honeypots"
            local file, err = io.open(file_path, "r")
            if not file then
                ngx.log(ngx.ERR, "Failed to open honeypots file: ", err)
                return
            end

            local uri = ngx.var.uri
            for line in file:lines() do
                ngx.log(ngx.INFO, "checking ", line)
                if uri:match(line) then
                    ngx.log(ngx.INFO, "matched! path: ", line)
                    ngx.var.upstream_target = "http://iocaine:42069"
                    break
                end
            end
            io.close(file)
        }

        proxy_pass $upstream_target;
    }
}