server {
    listen       80;
    server_name  localhost;

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    location / {
        proxy_pass http://anubis:8080;
    }
}

server {
    listen 8081;
    server_name localhost;

    location / {
        proxy_pass http://example:80;
    }

    location /asia/ {
        proxy_pass http://iocaine:42069;
    }

    location /sicily/ {
        proxy_pass http://iocaine:42069;
    }
}